config-version: 1

database:
  toggle: true
  # Table will be created when plugin is loaded
  table-name: 'user'
  username: 'root'
  password: ''
  name: 'starpvp'
  host: 'localhost'
  port: 'default'